name: ghautodoc

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  ghautodoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: kislyuk/ghautodoc/github-action-workflows/python-code-advisor@main
      with:
        openai-api-key: ${{secrets.OPENAI_API_KEY}}
