name: ghautodoc

on: [pull_request]

defaults:
  run: { shell: bash }

jobs:
  ghautodoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run script
      env:
        GITHUB_CONTEXT: ${{toJson(github)}}
      run: |
        pip install -Uq requests
        python .github/scripts/build-ghautodoc.py
