name: ghautodoc
on:
  workflow_dispatch:
  pull_request:
defaults:
  run: { shell: bash }

jobs:
  build:
    strategy:
      fail-fast: false
      matrix: { os: [ubuntu] }
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
      run: |
        pip install -Uq ghapi
        python .github/scripts/build-ghautodoc.py
